# Generated by Django 3.1.4 on 2020-12-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0002_ebook_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebook',
            name='thumbnail',
            field=models.ImageField(default='/default-img.png', upload_to='documents/'),
        ),
    ]
