# Generated by Django 3.1.4 on 2020-12-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0003_auto_20201202_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='deskripsi',
            field=models.TextField(default='Beautiful masterpiece'),
        ),
    ]
